version: '2.2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
        container_name: elasticsearch
        environment:
          - node.name=master-node
          - cluster.name=es-docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - xpack.security.enabled=false
          - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 2g
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
          - 9300:9300
    kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:7.13.0
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch

volumes:
    elasticsearch-data:
        driver: local